name: Go CI

permissions:
  contents: read

on:
  push:
    branches: [ '*', '*/*' ]

jobs:

  build:
    name: Test for Go ${{ matrix.gover }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        gover: ['~1.23', '~1.24', '~1.25', '~1.26']
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v6
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.gover }}
    - run: docker compose -f _env/standalone-docker/docker-compose.yml up -d
    - run: go build -v ./...
    - run: go test -v -run TestStandalone -cover ./...
